### PR TITLE
Merge upstream/master

### PR DESCRIPTION
**Pull request by mercedesb**
We're getting a lot of deprecation warnings from `stripe-ruby-mock` in the tests for https://github.com/ConvertKit/convertkit/pull/23703. 

Since we maintain our own fork, I pulled latest of the upstream and merged in. I'd like to see if this takes care of our deprecation warnings in our main app or not.

There were only 4 files with conflicts and in those cases, I made sure to keep the changes we made in our fork while merging them with whatever happened in upstream.

### CODE REVIEW

**Review by jonlunsford — COMMENTED** [review]
hehe.. I was also testing moving off of the fork, [here](https://github.com/ConvertKit/convertkit/pull/23741). Ruby 3.0 updates are still to be released, so merging main will get us the changes in [`3.1.0.rc1 (pre-release 2021-02-17)`](https://github.com/stripe-ruby-mock/stripe-ruby-mock/blob/master/CHANGELOG.md#310rc1-pre-release-2021-02-17)  now.

**Comment by mercedesb** [comment]
@jonlunsford Nice. I think we're still stuck with our fork for a little while. It looks like we've added some commerce stuff we definitely need based on [this diff](https://github.com/stripe-ruby-mock/stripe-ruby-mock/compare/master...ConvertKit:stripe-ruby-mock:main). 

I can go ahead and merge in [the PR that fixes the deprecation warnings](https://github.com/stripe-ruby-mock/stripe-ruby-mock/pull/747/files) in a subsequent PR if this feels like a good direction to go.

**Comment by jonlunsford** [comment]
@mercedesb it appears so, I'm surprised `stripe-ruby-mock` is this far behind Stripe.

I think updating this fork is the best way forward for now. Otherwise we're waiting on them to release `3.1`.

**Review by jonlunsford — APPROVED** [review]

**Review by christinalcole — APPROVED** [review]
🙇

**Pull request merged**
